// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.6.1
// source: proto/cosmos/accounts/defaults/ethbase/v1/ethbase.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgInit is used to initialize a base account.
type MsgInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// pub_key defines the pubkey for the account.
	PubKey []byte `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
}

func (x *MsgInit) Reset() {
	*x = MsgInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInit) ProtoMessage() {}

func (x *MsgInit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInit.ProtoReflect.Descriptor instead.
func (*MsgInit) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescGZIP(), []int{0}
}

func (x *MsgInit) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

// MsgInitResponse is the response returned after base account initialization.
// This is empty.
type MsgInitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgInitResponse) Reset() {
	*x = MsgInitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInitResponse) ProtoMessage() {}

func (x *MsgInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInitResponse.ProtoReflect.Descriptor instead.
func (*MsgInitResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescGZIP(), []int{1}
}

// MsgSwapPubKey is used to change the pubkey for the account.
type MsgSwapPubKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// new_pub_key defines the pubkey to swap the account to.
	NewPubKey []byte `protobuf:"bytes,1,opt,name=new_pub_key,json=newPubKey,proto3" json:"new_pub_key,omitempty"`
}

func (x *MsgSwapPubKey) Reset() {
	*x = MsgSwapPubKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSwapPubKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSwapPubKey) ProtoMessage() {}

func (x *MsgSwapPubKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSwapPubKey.ProtoReflect.Descriptor instead.
func (*MsgSwapPubKey) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescGZIP(), []int{2}
}

func (x *MsgSwapPubKey) GetNewPubKey() []byte {
	if x != nil {
		return x.NewPubKey
	}
	return nil
}

// MsgSwapPubKeyResponse is the response for the MsgSwapPubKey message.
// This is empty.
type MsgSwapPubKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgSwapPubKeyResponse) Reset() {
	*x = MsgSwapPubKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSwapPubKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSwapPubKeyResponse) ProtoMessage() {}

func (x *MsgSwapPubKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSwapPubKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgSwapPubKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescGZIP(), []int{3}
}

// QuerySequence is the request for the account sequence.
type QuerySequence struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuerySequence) Reset() {
	*x = QuerySequence{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuerySequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySequence) ProtoMessage() {}

func (x *QuerySequence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySequence.ProtoReflect.Descriptor instead.
func (*QuerySequence) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescGZIP(), []int{4}
}

// QuerySequenceResponse returns the sequence of the account.
type QuerySequenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sequence is the current sequence of the account.
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *QuerySequenceResponse) Reset() {
	*x = QuerySequenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuerySequenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySequenceResponse) ProtoMessage() {}

func (x *QuerySequenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySequenceResponse.ProtoReflect.Descriptor instead.
func (*QuerySequenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescGZIP(), []int{5}
}

func (x *QuerySequenceResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto protoreflect.FileDescriptor

var file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDesc = []byte{
	0x0a, 0x37, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73,
	0x2f, 0x65, 0x74, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x74, 0x68, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x73, 0x2e, 0x65, 0x74, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x22,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x75, 0x62,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b,
	0x65, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x53, 0x77, 0x61, 0x70,
	0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x75,
	0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6e, 0x65, 0x77,
	0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x53, 0x77, 0x61,
	0x70, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x0f, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x33, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73,
	0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x78, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x2f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x2f, 0x65, 0x74, 0x68, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescOnce sync.Once
	file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescData = file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDesc
)

func file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescGZIP() []byte {
	file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescOnce.Do(func() {
		file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescData)
	})
	return file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDescData
}

var file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_goTypes = []interface{}{
	(*MsgInit)(nil),               // 0: cosmos.accounts.defaults.ethbase.v1.MsgInit
	(*MsgInitResponse)(nil),       // 1: cosmos.accounts.defaults.ethbase.v1.MsgInitResponse
	(*MsgSwapPubKey)(nil),         // 2: cosmos.accounts.defaults.ethbase.v1.MsgSwapPubKey
	(*MsgSwapPubKeyResponse)(nil), // 3: cosmos.accounts.defaults.ethbase.v1.MsgSwapPubKeyResponse
	(*QuerySequence)(nil),         // 4: cosmos.accounts.defaults.ethbase.v1.QuerySequence
	(*QuerySequenceResponse)(nil), // 5: cosmos.accounts.defaults.ethbase.v1.QuerySequenceResponse
}
var file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_init() }
func file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_init() {
	if File_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgInitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSwapPubKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSwapPubKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuerySequence); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuerySequenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_goTypes,
		DependencyIndexes: file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_depIdxs,
		MessageInfos:      file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_msgTypes,
	}.Build()
	File_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto = out.File
	file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_rawDesc = nil
	file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_goTypes = nil
	file_proto_cosmos_accounts_defaults_ethbase_v1_ethbase_proto_depIdxs = nil
}
